import type { Customer } from './types';

export const mockCustomers: Customer[] = [
  {
    id: 'c-001',
    name: 'Amanda Lewis',
    email: 'amanda.lewis@email.com',
    phone: '+1-415-555-0112',
    country: 'United States',
    product_interest: 'Smoked brisket platter',
    status: 'new',
    source: 'instagram',
    created_at: '2026-03-29T10:15:00.000Z',
    tags: ['tourist'],
  },
  {
    id: 'c-002',
    name: 'Rizky Aditya',
    email: 'rizky.a@email.com',
    phone: '+62-812-2222-4444',
    country: 'Indonesia',
    product_interest: 'Family combo',
    status: 'contacted',
    source: 'landing_page',
    created_at: '2026-03-27T13:04:00.000Z',
    tags: ['repeat'],
  },
  {
    id: 'c-003',
    name: 'Chelsea Moore',
    email: 'chelsea.moore@email.com',
    phone: '+1-646-555-0189',
    country: 'United States',
    product_interest: 'Weekend brunch',
    status: 'converted',
    source: 'ads',
    created_at: '2026-03-23T18:20:00.000Z',
    tags: ['VIP', 'repeat'],
  },
  {
    id: 'c-004',
    name: 'Haruto Sato',
    email: 'haruto.sato@email.com',
    phone: '+81-70-1111-2233',
    country: 'Japan',
    product_interest: 'Steak menu',
    status: 'new',
    source: 'ads',
    created_at: '2026-04-02T08:05:00.000Z',
    tags: ['tourist'],
  },
];
